// <auto-generated />
using System;
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240815092443_modelsV4")]
    partial class modelsV4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API.Models.OrganizedEvent", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Place_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("User_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Usersid")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("last_login")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("Usersid");

                    b.ToTable("OrganizedEvent");
                });

            modelBuilder.Entity("API.Models.Participant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("OrganizedEventid")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ParticipatedEventid")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("User_FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("User_LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("User_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("OrganizedEventid");

                    b.HasIndex("ParticipatedEventid");

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("API.Models.ParticipatedEvent", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Place_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("User_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Usersid")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("last_login")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("Usersid");

                    b.ToTable("ParticipatedEvent");
                });

            modelBuilder.Entity("API.Models.Users", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordBackdoor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("last_login")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Models.OrganizedEvent", b =>
                {
                    b.HasOne("API.Models.Users", null)
                        .WithMany("OrganizedEvents")
                        .HasForeignKey("Usersid");
                });

            modelBuilder.Entity("API.Models.Participant", b =>
                {
                    b.HasOne("API.Models.OrganizedEvent", null)
                        .WithMany("Participants")
                        .HasForeignKey("OrganizedEventid");

                    b.HasOne("API.Models.ParticipatedEvent", null)
                        .WithMany("Participants")
                        .HasForeignKey("ParticipatedEventid");
                });

            modelBuilder.Entity("API.Models.ParticipatedEvent", b =>
                {
                    b.HasOne("API.Models.Users", null)
                        .WithMany("ParticipatedEvents")
                        .HasForeignKey("Usersid");
                });

            modelBuilder.Entity("API.Models.OrganizedEvent", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("API.Models.ParticipatedEvent", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("API.Models.Users", b =>
                {
                    b.Navigation("OrganizedEvents");

                    b.Navigation("ParticipatedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
