name: harmonyevent_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_gradient_button: ^0.0.1
  # flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  flutter_keychain: ^2.5.0
  # flutter_secure_storage_macos: ^3.0.1
  flutter_secure_storage_macos: ^3.1.2
  status_alert: ^1.0.1
  image_picker: ^1.1.2
  image_picker_macos: ^0.2.1+1
  shared_preferences: ^2.3.2
  dropdown_textfield: ^1.2.0
  simple_secure_storage: ^0.3.0

  # flutter_secure_storage: any
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/HE_Logo.png
  fonts:
    - family: Purisa
      fonts:
        # - asset: lib/fonts/PurisaBold.ttf
        # - asset: lib/fonts/PurisaBoldOblique.ttf
        # - asset: assets/purisamedium.ttf
        - asset: assets/purisabold.ttf
        
dependency_overrides:
  # temporary fix for https://github.com/mogol/flutter_secure_storage/issues/709
  flutter_secure_storage: 9.0.0
  flutter_secure_storage_linux: 1.2.0
  flutter_secure_storage_macos: 3.0.1
  flutter_secure_storage_platform_interface: 1.0.2
  flutter_secure_storage_windows: 3.0.0
  flutter_secure_storage_web:  1.2.0

# SECURE STORAGE VIRKER IKKE PÅ MACOS - UNDERSØGER LØSNINGSMULIGHEDER.
# HVIS DU BRUGER WINDOW ELLER ANDROID SÅ:
# - UDKOMMENTER flutter_secure_storage_macos: ^3.1.2 
# - SLET UDKOMMENTERINGEN AF # flutter_secure_storage: ^9.2.2
# - UDKOMMENTER ALLE dependency_overrides: